Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -5,9 +5,9 @@ name: Node.js CI
 
 on:
   push:
-    branches: [ main ]
+    branches: [main]
   pull_request:
-    branches: [ main ]
+    branches: [main]
   workflow_dispatch:
 
 jobs:
@@ -16,16 +16,16 @@ jobs:
     timeout-minutes: 5
     strategy:
       matrix:
-        os: [ubuntu-latest]
+        os: [ubuntu-latest, windows-latest, macos-latest]
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/setup-node@v3
-      with:
-        node-version-file: '.nvmrc'
-        cache: 'npm'
-    - run: npm ci
-    - name: Lint
-      run: npm run lint
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v3
+        with:
+          node-version-file: ".nvmrc"
+          cache: "npm"
+      - run: npm ci
+      - name: Lint
+        run: npm run lint
 
   build:
     runs-on: ${{ matrix.os }}
@@ -33,21 +33,48 @@ jobs:
     strategy:
       matrix:
         node-version: [16.x, 18.x, 20.x]
-        os: [ubuntu-20.04]
-
+        os: [ubuntu-20.04, windows-latest, macos-latest]
+        exclude:
+          - os: windows-latest
+            node-version: 16.x
+          - os: windows-latest
+            node-version: 18.x
+          - os: macos-latest
+            node-version: 16.x
+          - os: macos-latest
+            node-version: 18.x
     steps:
-    - uses: actions/checkout@v4
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v3
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-    - run: npm ci
-    - name: Build and Statically Render
-      run: npm run predeploy
-      env:
-        NODE_ENV: development
-    - name: Test
-      run: npm test
-      env:
-        NODE_ENV: development
+      - uses: actions/checkout@v4
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: "npm"
+      - run: npm ci
+      - name: Build and Statically Render
+        shell: bash
+        run: |
+          function retry {
+            local n=1
+            local max=5
+            local delay=1
+            while true; do
+              "$@" && break || {
+                if [[ $n -lt $max ]]; then
+                  ((n++))
+                  echo "Command failed. Attempt $n/$max:"
+                  sleep $delay;
+                else
+                  echo "The command has failed after $n attempts."
+                  return 1
+                fi
+              }
+            done
+          }
+          retry npm run predeploy
+        env:
+          NODE_ENV: development
+      - name: Test
+        run: npm test
+        env:
+          NODE_ENV: development
